config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show'

  # ,as: 'show_home'
  devise_for :users

  get "/home/about" => "homes#about" , as: 'about_home'

  # resources :homes, only: [:edit, :update, :index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'homes' => 'homes#show'

  resources :users, only: [:show, :edit, :update, :index, :create]
  resources :books, only: [:new, :create, :show, :edit, :update, :index, :destroy]

  resources :homes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title,
		presence: true

	validates :body,
		presence: true, length:{maximum:20}

	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :name, presence: true, length:{in: 2..20}

  validates :introduction, length:{maximum:50}
 

  #画像投稿ができるようにするための記述
  attachment :profile_image

  has_many :books, dependent: :destroy
  
  def email_required?
    false
  end


  def email_changed?
    false
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	#ログインユーザーのみ下記アクションが実行できる。
	# before_action :authenticate_user!
	# before_action :configure_permitted_parameters, if: :devise_controller?
  	
	def after_sign_in_path_for(resource)
		user_path(current_user.id)
	end

	def after_sign_up_path_for(resource)
		user_path(current_user.id)
	end

	def after_sign_out_path_for(resource)
		homes_path
	end

  	protected
 	def configure_permitted_parameters
 		added_attrs_1 = [ :email, :name, :password, :password_confirmation ]
    	devise_parameter_sanitizer.permit :sign_up, keys: added_attrs_1
    	added_attrs_2 = [:name, :password, :password_confirmation]
    	devise_parameter_sanitizer.permit :sign_in, keys: added_attrs_2
  	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!

	def index
		@books = Book.all
		@book = Book.new
		@user = User.find(current_user.id)
	end

	def show
		@book = Book.find(params[:id])
		@book_new = Book.new
		@user = User.find(@book.user_id)
	end


	def edit
		@book = Book.find(params[:id])
		# :id/editのurlではこの画面に遷移できないように条件分岐させる
		if @book.user_id == current_user.id
		  
		else
			redirect_to books_path
		end

	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
		   redirect_to(book_path(@book.id), notice:'book was successfully created')
		 else
		   @books = Book.all
		   @user = User.find(current_user.id)
		   render :index
		end
	end


	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		   redirect_to(book_path(@book.id), notice:'book was successfully created')

		else
			render :edit
		end
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to(books_path, notice:'book was successfully deleted')
	end

	private

	def book_params
		params.require(:book).permit(:title, :body)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def new
	end

	def create
	end

	def index
	end

	def about
		
	end

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_action :authenticate_user!
  def show
    @book = Book.new
    @myuser = User.find(current_user.id)
    @linkuser = User.find(params[:id])
    if @myuser == @linkuser
  	   @user = User.find(current_user.id)
       @books = Book.where(user_id:@user)
    else
       @user = User.find(params[:id])
       @books = Book.where(user_id:@user)
    end
  end

  def edit
  	  @user = User.find(params[:id])
      if @user == current_user

      else
         redirect_to user_path(current_user.id)
      end
  end
  	
  def update
  	  @user = User.find(params[:id])
  	  if @user.update(user_params)
  	     redirect_to(user_path(current_user.id), notice:'User was successfully updated')

      else
         render "users/edit"
      end
  end

  def index
  	  @users = User.all
  	  @user = User.find(current_user.id)
      @book =Book.new
  end

  def create
      @book = Book.new(book_params)
      if @book.save
         redirect_to(book_path(@book.id), notice:'book was successfully created')
      else
        @books = Book.all
        @users = User.all
        @user = User.find(current_user.id)
        render "users/index"
      end
    
  end

  private

  def user_params
  	  params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class = "container">
	<div class = "col-lg-3">
	</div>

	<div class = "col-lg-6">

		<h1 class = "edit">Editing Book</h1>
		<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
			<div class = "new_main">

				<%= render 'layouts/erorr-messages-books', book:@book %>

			</div>
		<h4 class = "edit">Title</h4>
		<div><%= f.text_field :title,class:"form-control" %></div>

		<h4 class = "edit">Opinion</h4>
			<div><%= f.text_area :body,class:"form-control"  %></div>
				<br>
			<div class = "edit"><%= f.submit 'Update Book', class:"btn btn-primary btn-block"  %></div>
		<% end %>
		<p class = "edit">
		<%=link_to "Show", book_path(@book.id) %> | <%=link_to "Back", books_path %>
		</p>

	</div>

	<div class = "col-lg-3">
	</div>
</div>


app/views/books/index.html.erb
<div class = "container">
<p><%= notice %></p>

		<%= render 'layouts/erorr-messages-books', book:@book %>


	<div class = "row">
			<div class = "col-xs-3">
				<%= render 'layouts/sidbar', user:@user,book:@book %>
			</div>

<!-- 投稿したbook一覧 -->
	
	<div class = "col-xs-9">
		<%= render 'layouts/books-index', books:@books,users:@users,user:@user %>


	</div>
	</div>
</div>

app/views/books/show.html.erb
<div class = "container">

<p><%= notice %></p>


<div class = "row">
	<div class = "col-xs-3">
		<%= render 'layouts/sidbar', user:@user,book:@book %>
	</div>


<h2>Book detail</h2>
<div class = "col-xs-9">
		<table class = "table">
			<tbody>
				<tr>
					<td>
					<%= link_to attachment_image_tag( @user, :profile_image, size: "50x50", class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"), user_path(@user) %>
						<br>
						<br>
						<br>
						<%= link_to @user.name,user_path(@user) %>

					</td>
					<td><%= @book.title %></td>
					<td><%= @book.body%></td>

					<% if  @user.id == current_user.id %>
					<td><%=link_to "Edit", edit_book_path(@book.id) %></td>
					<td><%= link_to "Destroy", book_path(@book.id), method: :delete, data: {confirm: "Are you sure?" } %></td>
					<% end %>
				</tr>
				</tbody>
		</table>

</div>
</div>
</div>


app/views/homes/about.html.erb
<div class = "container">
	<div class = "row">
		<div class = "col-lg-1">
		</div>
		<div class = "col-lg-11">
			<h1>welcom to <span class = "glyphicon glyphicon-book"><strong>Bookers !!</strong></h1>
		</div>
	<div>
<div>

app/views/homes/index.html.erb
<div class = "container">

	<% if notice %>
		<p><%= notice %></p>
	<% end %>
	<% if alert %>
	   <p><%= alert %></p>
	<% end %>
	<div class = "row">
		<div class = "col-lg-3">
		</div>
		<div class = "col-lg-6">
			<h1>welcom to <span class = "glyphicon glyphicon-book"><strong>Bookers !!</strong></h1>

			<p>In <span class = "glyphicon glyphicon-book"><strong>Bookers,</strong></p><br>
			<p>you can share and exchange your opinions, inpressions, and emotions</p><br>
			<p>about verious books!</p>
			<p>
			<%= link_to "Log in",  new_user_session_path,class:"btn btn-success btn-block" %>
			</p>

			
			<%= link_to "Sign up", new_user_registration_path,class:"btn  btn-info btn-block " %>
			</p>
		</div>
		<div class = "col-lg-3">
		</div>
	</div>
</div>



app/views/homes/show.html.erb
<div class = "container">

	<% if notice %>
		<p><%= notice %></p>
	<% end %>
	<% if alert %>
	   <p><%= alert %></p>
	<% end %>
	<div class = "row">
		<div class = "col-lg-3">
		</div>
		<div class = "col-lg-6">
			<h1>welcom to <span class = "glyphicon glyphicon-book"><strong>Bookers !!</strong></h1>

			<p>In <span class = "glyphicon glyphicon-book"><strong>Bookers,</strong></p><br>
			<p>you can share and exchange your opinions, inpressions, and emotions</p><br>
			<p>about verious books!</p>
			<p>
			<%= link_to "Log in",  new_user_session_path,class:"btn btn-success btn-block" %>
			</p>

			
			<%= link_to "Sign up", new_user_registration_path,class:"btn  btn-info btn-block " %>
			</p>
		</div>
		<div class = "col-lg-3">
		</div>
	</div>
</div>



app/views/layouts/_books-index.html.erb
<table class = "table">
	<h3>Books</h3>
	<thead>
		<tr>
			<th>profileimage</th>
			<th>title</th>
			<th>opinion</th>
		</tr>
	</thead>

	<tbody>
		<% books.each do |book| %>
		<% users = User.find(book.user_id) %>
			<tr>
				<td>
					<%= link_to attachment_image_tag(users, :profile_image, size: "50x50", class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"), user_path(users) %>
				</td>

				<td><%= link_to book.title, book_path(book.id) %></td>
				<td><%= book.body %></td>
			</tr>
		<% end %>
	</tbody>

</table>

app/views/layouts/_erorr-messages-books.html.erb
	<% if book.errors.any? %>
	<ul>
		<% book.errors.full_messages.each do |message| %>
			<li class = "error_message">error:<%= message %></li>
		<% end %>
    </ul>
	<% end %>

app/views/layouts/_sidbar.html.erb
<h3>User info</h3>
	<div class = "profile_image">
		<%= attachment_image_tag @user, :profile_image, size: "100x100", class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
	</div>

	<table class = "table">
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		</table>

		<% if @user.id == current_user.id %>
	        <p><%= link_to "", edit_user_path(@user), class:"btn btn-default btn-lg btn-block glyphicon glyphicon-wrench"%>
		        </p>
		<% end %>

		<h2 class = "">New book</h2>

		<%= form_for(book) do |f| %>

			<h4>title</h4>
			<%= f.text_field :title, class:"form-group form-control" %>

			<h4>body</h4>
			<%= f.text_area :body, class:"form-group form-control" %>

			<br>
			<%= f.submit 'Create Book', class:"btn btn-primary btn-block" %>
		<% end %>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task2Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class = "header_main">
   <nav class = "navbar navbar-fixed-top navbar-inverse">
    <div class = "container">
      <div class = "row">
        <div class = "navbar navbar-nav navbar-left">
          <span class = "header_title">Bookers</span>
        </div>
        <ul class = "nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <!-- link_toのshowへのpathはshowと書かない
              editの場合は、edit_user_pathになる -->
                <%= link_to ' Home', user_path(current_user.id),class:"glyphicon glyphicon-home home" %>
              </li>
              <li>
                <%= link_to ' Users', users_path, class:"glyphicon glyphicon-user users"%>
              </li>
              <li>
                <%= link_to ' Books', books_path,  class:"glyphicon glyphicon-book books" %>
            </li>

            <li>
               <%= link_to " logout", destroy_user_session_path, method: :delete,  class:"glyphicon glyphicon-log-out logout" %>
            </li>
          </ul>
          <% else %>
            <ul class = "nav navbar-nav navbar-right">
              <!--  リンクの書き方 正解root_path
                ここで、show_homesを書いても同じ動きをするが、表示されるURLが指定のものと異なる
              -->

              <li>
                <%= link_to " Home", root_path, class:"glyphicon glyphicon-home home" %>
              </li>

              <li>
                <%= link_to " About", about_home_path, class:"glyphicon glyphicon-link abouts" %>
              </li>

              <li>
                <%= link_to " sign up", new_user_registration_path, class:"glyphicon glyphicon-edit sign_up"  %>
               </li>
                <li class="">
                <%= link_to " login",  new_user_session_path, class:"glyphicon glyphicon-log-in sign-in"  %>
                </li>
              </ul>
          <% end %>
        </div>
      </div>
    </nav>
  </header>
  <main>
    <br>
    <br>
    <br>
    <%= yield %>
  </main>

<footer>
  <div class = "container">
    <div class = "row">
      <div class = "col-lg-9"></div>
        <div class = "col-lg-3">
          <p>CopyRight Intratop.inc</p>
        </div>
      </div>
  </div>
</footer>
</body>
</html>

app/views/users/edit.html.erb
<div class = "container">
	<div class = "col-lg-1">
	</div>

	<div class = "col-lg-3">

		<h2>User info</h2>
		
			<% if @user.errors.any? %>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li class = "error_message">error:<%= message %></li>
				<% end %>
			  </ul>
			<% end %>
		

				<%= form_for(@user) do |f| %>
					<p>name</p>
					<%= f.text_field :name, autofocus: true %>


					<p>image(プロフィール画像)</p>
					 <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>

					<p>introduction</p>
					<%= f.text_area :introduction, autofocus: true  %>
					<%= f.submit "Update User" %>
				<% end %>
			

	</div>

<div class = "col-lg-8">
</div>
</div>


app/views/users/index.html.erb
<div class = "container">
	<% if notice %>
		<p><%= notice %></p>
	<% end %>
	<% if alert %>
	   <p><%= alert %></p>
	<% end %>

	<div class = "row">
		<div class = "col-xs-3">
			<%= render 'layouts/sidbar', user:@user,book:@book %>
		</div>

	<div class = "col-xs-9">
	<h3>users</h3>
		<table class = "table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td>
							<%= attachment_image_tag user, :profile_image, size: "50x50", class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
						</td>

						<td><%= user.name %></tb></td>
						<td><%=link_to "Show", user_path(user.id) %></td>
					</tr>
					<% end %>
				
				</tbody>
			</table>

	</div>
</div>
</div>

app/views/users/show.html.erb
<div class = "container">
	<% if notice %>
		<p><%= notice %></p>
	<% end %>
	<% if alert %>
	   <p><%= alert %></p>
	<% end %>

	<%= render 'layouts/erorr-messages-books', book:@book %>

	<div class = "row">
		<div class = "col-xs-3">
			<%= render 'layouts/sidbar', user:@user,book:@book %>
		</div>

	<div class = "col-xs-9">
		<%= render 'layouts/books-index', books:@books,users:@users,user:@user %>
	
	</div>
</div>
</div>